### ISSUE TITLE
problem with file mode declaration

### ISSUE THREAD

**Issue by ryayon** [NERC-CEH/puppet-fstab#4]
Hi,

I get the following issue with Puppet 4.5.2 declaring the credentials file:

`Error: Failed to apply catalog: Parameter mode failed on File[/root/mount.smb]: The file mode specification must be a string, not 'Fixnum' at /etc/puppetlabs/code/environments/hotfix/modules/fstab/manifests/mount.pp:28
`

To fix that, just replace `mode    => 400,` with `mode    => '0400',` on line 28 of  `mount.pp`.

PS: do you want a PR?

**Comment by noqqe** [comment]
Just had the same issue.
