### ISSUE TITLE
Relax requirement on puppetlabs-concat 

### ISSUE THREAD

**Issue by bschonec** [NERC-CEH/puppet-fstab#7]
Puppetlabs concat is now at 2.2.0.  The 2.0.0 requirement makes it difficult to upgrade.

I have tested puppet-fstab with version 2.2.0 successfully.

See #9

**Comment by lardymike** [comment]
PR accepted and merged.

**Comment by SirUrban** [comment]
But now it still says "<2.2.0" which is wrong, isn't it? Shouldn't it be "<=2.2.0"?
